# Aprendizaje Supervisado: 

#### - Supervisado: Entrenamiento por medio de datos etiquetados.

#### - No Supervisados: Entrenamiento por medio de clasificacion y organizacion de datos ( Datos no etiquetados )

### Prepocesamiento de datos

In [4]:
# Librerias

import numpy as np
from sklearn import preprocessing

# Datos

input_data = np.array([[5.1, -2.9, 3.3],
                     [-1.2, 7.8, -6.1],
                     [3.9, 0.4, 2.1],
                     [7.3, -9.9, -4.5]])

#### Binarizacion:

In [11]:
# Binarizacion de "input_data" 

data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data) # Threshold = Límite.
print("Binarized data:\n", data_binarized)

Binarized data:
 [[ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]


#### Eliminación de la Media:

In [13]:
# Desviacion estandar y media.

print("Before:")
print("Mean =", input_data.mean(axis=0))
print("Std Deviation=", input_data.std(axis=0))

Before:
Mean = [ 3.775 -1.15  -1.3  ]
Std Deviation= [ 3.12039661  6.36651396  4.0620192 ]


In [15]:
# Eliminacion de la media.

deta_scaled = preprocessing.scale(input_data)
print("After:")
print("Mean =", deta_scaled.mean(axis=0))
print("Std Deviation", deta_scaled.std(axis=0))

After:
Mean = [  1.11022302e-16   0.00000000e+00   2.77555756e-17]
Std Deviation [ 1.  1.  1.]


#### Escalado:

In [20]:
# Las características de los valores varian en muchos valores aleatorios. Cuando se escala esos valores aleatorios se reducen.

# Escalado Minimo y Escalado Maximo.

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1)) # Parametro de escalado.
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data) # Variable a escalar

print("Datos escalados en un minimo y un maximo: \n", data_scaled_minmax)

Datos escalados en un minimo y un maximo: 
 [[ 0.74117647  0.39548023  1.        ]
 [ 0.          1.          0.        ]
 [ 0.6         0.5819209   0.87234043]
 [ 1.          0.          0.17021277]]


#### Normalización:

In [24]:
# Los vectores pueden ser medidos en una escala común. Existen dos:
# L1: Least Absolute Deviation (Minimos Errores Absolutos): La suma de valores absolutos debe ser 1 en cada fila.
# L2: Least Squares (Minimos Cuadrados): La suma de los cuadrados debe ser uno

# Normalizacón de nuestros datos: 

# L1

data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
print("\nDatos L1:", data_normalized_l1)

# L2

data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nDatos L2:", data_normalized_l2)


Datos L1: [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]

Datos L2: [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]


#### Codificación de etiquetas:

In [26]:
# Datos de ejemplo.

input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']

# Codificador de etiquetas.

encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

print('\nLabels mappings')
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)


Labels mappings
black --> 0
green --> 1
red --> 2
white --> 3
yellow --> 4


In [31]:
# Codificacion de datos:

test_labels = ['green', 'red', 'black']
encoded_values = encoder.transform(test_labels)
print('\nLabels =', test_labels)
print('Encoded values = ', list(encoded_values))


Labels = ['green', 'red', 'black']
Encoded values =  [1, 2, 0]


In [32]:
# Decodificación de datos:

encode_values = [3, 0, 4, 1]
decoded_list = encoder.inverse_transform(encoded_values)
print('\nEncoded values =', encoded_values)
print('Decoded labels=', list(decoded_list))


Encoded values = [1 2 0]
Decoded labels= ['green', 'red', 'black']


#### Regresión l